naomis_dict = {
    'NN5': ['capitalism', 'inadequacy', 'accelerator'],
    'NNS5': ['refrigerators', 'universities', 'qualifications'],
    'D1': ['the', 'a'],
    'NN4': ['operator', 'geography', 'enthusiast'],
    'NNS4': ['apologies', 'cafeterias', 'relocations'],
    'D2': ['many', 'several', 'little'],
    'Adj2': ['rounded', 'wooden', 'sheepish'],
    'NN1': ['dog', 'lime', 'road'],
    'NNS1': ['pills', 'tubs', 'cooks'],
    'P2': ['above', 'behind', 'betwixt'],
    'NN2': ['blanket', 'vision', 'package'],
    'P1': ['of', 'on', 'in'],
    'NNS3': ['hairdryers', 'notaries', 'SUVs'],
    'V3': ['polishing', 'amplify', 'edify'],
    'V1': ['meow', 'warm', 'ping'],
}
